[Qualified EXPs in 0.10.0 firmware]
    < 2025.05.08, DR1, 8SQ_aTa0417_3, (q1, q3) >
        - tested:
            -- m1, m2, m3, m4, m7, m8, m10a, m11, m13a, m13b, m13c, m14
            -- c1, c2, c3, c5, c6
            -- x2
            -- a2
        - haven't been tested:
            -- m5, m6, m9, m10b
            -- t1
            -- a1, a3
            -- c4 (abandoned)