QD_file: qblox_drive_AS/QD_backup/20250508/DR1#11_SumInfo.pkl
Chip name: Test_8SQ
Comments: ---

RO-atte = 32 dB
XY-atte = 0 dB
TOF = 232 ns
Active Reset OFF, Reset time = 1000 us

[q0]
    bare    = 0.0 GHz
    ROF     = 6.0 GHz
    RO-amp  = 0.5 V
    ROT     = 1.0 us
    f01     = 4.0 GHz
    GE-amp  = 0.05 V
    GE-dura = 40.0 ns
    EF-dura = 40.0 ns
    Motzoi  = 0
    x       = 6000.0 MHz
    g       = 0.0 MHz
    Ec      = 0.0 MHz

[q1]
    bare    = 4.912285740134493 GHz
    ROF     = 4.912544786800924 GHz
    RO-amp  = 0.05 V
    ROT     = 15.0 us
    f01     = 3.0850000000000004 GHz
    GE-amp  = 0.3310315065647449 V
    GE-dura = 300.0 ns
    EF-dura = 40.0 ns
    Motzoi  = 0
    x       = 0.259046666431427 MHz
    g       = 0.0 MHz
    Ec      = 0.0 MHz

[q2]
    bare    = 0.0 GHz
    ROF     = 6.0 GHz
    RO-amp  = 0.5 V
    ROT     = 1.0 us
    f01     = 4.0 GHz
    GE-amp  = 0.05 V
    GE-dura = 40.0 ns
    EF-dura = 40.0 ns
    Motzoi  = 0
    x       = 6000.0 MHz
    g       = 0.0 MHz
    Ec      = 0.0 MHz

[q3]
    bare    = 5.113070735601589 GHz
    ROF     = 5.113501679029422 GHz
    RO-amp  = 0.05 V
    ROT     = 15.0 us
    f01     = 3.3790340697999537 GHz
    GE-amp  = 0.4166805407529241 V
    GE-dura = 300.0 ns
    EF-dura = 40.0 ns
    Motzoi  = 0
    x       = 0.4309434278335571 MHz
    g       = 0.0 MHz
    Ec      = 0.0 MHz

